# Generated by Django 4.2.5 on 2023-09-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('heel_height', models.CharField(max_length=50)),
                ('insole', models.CharField(max_length=50)),
                ('closure', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=50)),
                ('toestyle', models.CharField(max_length=50)),
            ],
        ),
    ]
