# Generated by Django 4.2.5 on 2023-09-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solemate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='brand',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sneaker',
            name='color',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sneaker',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sneaker',
            name='price',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sneaker',
            name='url',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
