# Generated by Django 4.2.5 on 2023-10-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solemate', '0002_sneaker_brand_sneaker_color_sneaker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='closure',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='heel_height',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='insole',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='material',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='toestyle',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='url',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='cid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
