# Generated by Django 4.2.5 on 2023-10-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('cid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
